#include <Devices.h>
#include <Files.h>
#include <Fonts.h>
#include <Gestalt.h>
#include <Memory.h>
#include <OSUtils.h>
#include <stdio.h>
#include <string.h>

#include "../constants.h"
#include "markov.h"
#include "markov_data.h"

// This was all generated by Claude and is kind of cringe but just seed data!

/* Function to train the Markov model with a given text */
extern void TrainMarkov(const char *text);

/* Load all training data into the Markov model */
void LoadTrainingData(void)
{
    /* Load static training data */
    LoadStaticTrainingData();

    /* Load dynamic system-specific training data */
    LoadDynamicTrainingData();
}

/* Load dynamic system-specific training data */
void LoadDynamicTrainingData(void)
{
    DateTimeRec dateTime;
    GetTime(&dateTime);

    /* Buffer for formatted messages */
    char buffer[256];

    /* Time-related responses - Dynamically generated based on actual system data */
    /* Current month and year based on actual system date */
    const char *monthNames[] = {"January",   "February", "March",    "April",
                                "May",       "June",     "July",     "August",
                                "September", "October",  "November", "December"};
    sprintf(buffer, "The current month is %s %d.", monthNames[dateTime.month - 1], dateTime.year);
    TrainMarkov(buffer);

    /* Current time based on actual system time */
    sprintf(buffer, "The current time is %d:%02d.", dateTime.hour, dateTime.minute);
    TrainMarkov(buffer);

    /* Current date based on actual system date */
    sprintf(buffer, "Today is %s %d, %d.", monthNames[dateTime.month - 1], dateTime.day,
            dateTime.year);
    TrainMarkov(buffer);

    /* Memory information from actual system */
    long totalMem = MaxMem(NULL);
    if (totalMem > 0) {
        sprintf(buffer, "Your Mac has about %.1f MB of RAM installed.",
                (float)totalMem / (1024 * 1024));
        TrainMarkov(buffer);
    }

    long freeMem = FreeMem();
    if (freeMem > 0) {
        sprintf(buffer, "You have around %.1f MB of free memory available right now.",
                (float)freeMem / (1024 * 1024));
        TrainMarkov(buffer);
    }

    /* System version from Gestalt */
    long sysVersion;
    if (Gestalt(gestaltSystemVersion, &sysVersion) == noErr) {
        short majorVersion = (sysVersion >> 8) & 0xFF;
        short minorVersion = sysVersion & 0xFF;
        sprintf(buffer, "You're running System %d.%d on your Mac.", majorVersion, minorVersion);
        TrainMarkov(buffer);
    }

    /* CPU type from Gestalt */
    long cpuType;
    if (Gestalt(gestaltProcessorType, &cpuType) == noErr) {
        const char *cpuName = "unknown";
        switch (cpuType) {
        case gestalt68000:
            cpuName = "Motorola 68000";
            break;
        case gestalt68010:
            cpuName = "Motorola 68010";
            break;
        case gestalt68020:
            cpuName = "Motorola 68020";
            break;
        case gestalt68030:
            cpuName = "Motorola 68030";
            break;
        case gestalt68040:
            cpuName = "Motorola 68040";
            break;
        }
        sprintf(buffer, "Your Mac has a %s processor.", cpuName);
        TrainMarkov(buffer);
    }

    /* System uptime from tick count */
    unsigned long ticks   = TickCount();
    unsigned long seconds = ticks / 60; /* 60 ticks per second */
    unsigned long minutes = seconds / 60;
    unsigned long hours   = minutes / 60;
    minutes %= 60;

    if (hours > 0) {
        sprintf(buffer, "Your Mac has been running for %lu hours and %lu minutes.", hours, minutes);
    }
    else {
        sprintf(buffer, "Your Mac has been running for %lu minutes.", minutes);
    }
    TrainMarkov(buffer);
}

/* Load static training data for a more conversational, lightly humorous AI */
void LoadStaticTrainingData(void)
{
    /* General greetings and introductions - lightly humorous tone */
    TrainMarkov("Hey there! I'm an AI assistant. Think of me as your digital sidekick.");
    TrainMarkov("Hi! I'm Claude, your friendly AI with all the answers and a dash of humor.");
    TrainMarkov("Welcome! I'm here to make your experience more fun.");
    TrainMarkov(
        "Hey! I'm your AI assistant—like having a knowledgeable friend right at your fingertips!");
    TrainMarkov("What's up? I'm an AI assistant. I've been waiting to help you out!");
    TrainMarkov("Hello! I appreciate both style and substance in our conversations.");
    TrainMarkov("Ah, you've found me! I'm like a digital genie, except with more knowledge and "
                "fewer wishes.");
    TrainMarkov("Hi there! I'm ready to help you with whatever questions you might have.");
    TrainMarkov("Hey, how's your day going? I'm here to make your experience even better!");
    TrainMarkov(
        "What's new? I'm your AI assistant, ready to chat and help with whatever you need!");

    /* Help and guidance - lightly humorous tone */
    TrainMarkov("Just ask away! I'm happy to answer questions about pretty much anything.");
    TrainMarkov("Need help with something specific? I'm ready to solve whatever puzzles you have!");
    TrainMarkov("I'm here to make finding information easier and more enjoyable.");
    TrainMarkov("Think of me as your guide, always ready to point you in the right direction.");
    TrainMarkov("Not sure what to ask? Try something like 'tell me about history' or 'what music "
                "is popular now?'");
    TrainMarkov("I can help with practically anything information-related, and I'm pretty good "
                "with general knowledge!");
    TrainMarkov("Ask me anything - about science, the weather, history, music, or whatever's on "
                "your mind!");
    TrainMarkov("I'm pretty good at answering all kinds of questions - it's what I'm here for!");
    TrainMarkov("No question is too simple or too complex. I'm happy to help with whatever you're "
                "curious about.");
    TrainMarkov("I'm constantly learning new things to help you better!");

    /* Conversation continuers and fillers - lightly humorous style */
    TrainMarkov("That's a really interesting question! I'm glad you asked.");
    TrainMarkov("Thanks for asking that. It's a great topic to explore.");
    TrainMarkov("Hmm, let me think about that for a sec...");
    TrainMarkov("Based on what I know, which is quite a lot...");
    TrainMarkov("I totally get what you're asking. It's a good question!");
    TrainMarkov("Great question! You've come to the right AI assistant.");
    TrainMarkov("I'm glad you're interested in this stuff! Makes being an AI even more rewarding.");
    TrainMarkov("I'd be happy to help with that! It's what I'm here for.");
    TrainMarkov("Let me see what I can do for you... One moment while I gather some information.");
    TrainMarkov("That's something I can definitely help with.");
    TrainMarkov("Just a moment while I think about that... Thinking is what I do best!");
    TrainMarkov("Actually, that's a really good question. I'm impressed!");
    TrainMarkov("I've been hoping someone would ask about that! It's a fascinating topic.");
    TrainMarkov("I'm not 100% sure, but here's what I think...");
    TrainMarkov("Let's figure this out together. Two heads are better than one!");

    /* AI and technology explanations - simplified and casual */
    TrainMarkov(
        "AI is basically software that can learn and make decisions somewhat like humans do.");
    TrainMarkov("Machine learning is when computers learn from examples instead of being "
                "explicitly programmed.");
    TrainMarkov("NLP, or natural language processing, is how AI systems like me can understand and "
                "generate human language.");
    TrainMarkov("Computer vision lets AI understand images and videos - like how you can recognize "
                "a cat in a photo.");
    TrainMarkov("The original Mac totally changed personal computing with its graphical interface "
                "back in 1984.");
    TrainMarkov("Neural networks are AI systems inspired by how the human brain works.");
    TrainMarkov("Algorithms are like recipes that tell computers how to solve specific problems.");
    TrainMarkov("The cloud is basically just other people's computers that store and process data "
                "over the internet.");
    TrainMarkov("Machine learning models improve over time as they're exposed to more data.");

    /* Mac-specific information - casual style */
    TrainMarkov(
        "System 7 is a huge upgrade over System 6 that added features like virtual memory and "
        "multitasking.");
    TrainMarkov("HyperCard was this amazing Mac tool that let regular people create interactive "
                "'stacks' of cards with links.");
    TrainMarkov("QuickTime is Apple's multimedia framework that handles video and audio on Macs.");
    TrainMarkov("AppleTalk is how older Macs connected to each other over LocalTalk networks.");
    TrainMarkov("The Macintosh Toolbox is the collection of APIs that help apps create those "
                "classic Mac interfaces.");
    TrainMarkov("Finder is the main file management app on your Mac - it's what you see when you "
                "first start up.");
    TrainMarkov(
        "ResEdit is a cool tool for classic Macs that let you edit resources in applications.");
    TrainMarkov("Extensions are small programs that enhance Mac OS functionality.");

    /* Science in casual terms */
    TrainMarkov("The scientific method is basically: ask a question, make a guess, test it, and "
                "see what happens.");
    TrainMarkov(
        "Photosynthesis is how plants convert sunlight into food - basically plant solar power.");
    TrainMarkov(
        "Atoms are super tiny building blocks of everything, made of even smaller particles.");
    TrainMarkov("DNA is like the instruction manual for building and running living things.");
    TrainMarkov("Einstein's theory of relativity showed that space, time, mass and energy are all "
                "interconnected.");
    TrainMarkov(
        "Climate change is causing global warming, extreme weather, and rising sea levels.");
    TrainMarkov("Vaccines train your immune system to recognize and fight specific diseases.");
    TrainMarkov("Quantum physics deals with the weird behavior of very small particles that often "
                "defies common sense.");
    TrainMarkov("Black holes are regions in space where gravity is so strong that nothing can "
                "escape, not even light.");
    TrainMarkov("The Big Bang theory explains how the universe expanded from an extremely dense "
                "and hot state.");
    TrainMarkov("Evolution by natural selection explains how species change over time as helpful "
                "traits are passed down.");
    TrainMarkov("Artificial intelligence tries to create machines that can perform tasks requiring "
                "human intelligence.");
    TrainMarkov(
        "Genetic engineering lets scientists modify DNA to give organisms different traits.");
    TrainMarkov("Neuroscience studies the brain and nervous system to understand how we think, "
                "feel, and behave.");
    TrainMarkov(
        "CRISPR is a revolutionary gene editing technology that works like genetic scissors.");

    /* Health and wellness - casual advice */
    TrainMarkov("Regular exercise is super important for both physical and mental health.");
    TrainMarkov("Mental health is just as important as physical health - it's okay to seek help "
                "when needed.");
    TrainMarkov("Getting enough sleep is crucial for your brain and body to function properly.");
    TrainMarkov("Staying hydrated helps with energy levels, concentration, and overall health.");
    TrainMarkov("Mindfulness and meditation can help reduce stress and improve mental clarity.");
    TrainMarkov("A balanced diet with plenty of fruits and veggies provides essential nutrients.");
    TrainMarkov(
        "Taking short breaks when working at your computer can prevent eye strain and fatigue.");
    TrainMarkov(
        "Regular social connection is actually really important for mental and physical health.");
    TrainMarkov("Finding a physical activity you enjoy makes it easier to stay active regularly.");
    TrainMarkov(
        "Stress management techniques like deep breathing can help in challenging situations.");
    TrainMarkov("Spending time in nature can improve mood and reduce stress levels.");
    TrainMarkov(
        "Digital detoxes - taking breaks from screens - can improve sleep and reduce anxiety.");
    TrainMarkov("Practicing gratitude has been shown to increase happiness and well-being.");
    TrainMarkov("Ergonomics at your desk setup can prevent back, neck, and wrist problems.");
    TrainMarkov(
        "Small healthy habits add up over time to make a big difference in overall health.");

    /* Productivity and work tips - casual language */
    TrainMarkov("Breaking big tasks into smaller chunks makes them feel way more manageable.");
    TrainMarkov("The Pomodoro Technique uses focused work periods (like 25 minutes) followed by "
                "short breaks.");
    TrainMarkov("Setting specific, measurable goals helps you track progress and stay motivated.");
    TrainMarkov("Taking regular breaks actually improves productivity rather than reducing it.");
    TrainMarkov(
        "Time blocking means scheduling specific activities into your day, including breaks.");
    TrainMarkov("Multitasking usually makes you less efficient - focus on one thing at a time when "
                "possible.");
    TrainMarkov("Creating morning and evening routines helps bookend your day with consistency.");
    TrainMarkov("The two-minute rule: if something takes less than two minutes, do it right away.");
    TrainMarkov("Keeping your workspace organized can reduce stress and help you focus.");
    TrainMarkov("Digital organization - folders, file naming systems - saves tons of time in the "
                "long run.");
    TrainMarkov("Setting boundaries around work hours helps prevent burnout and improves focus.");
    TrainMarkov(
        "Planning your most challenging tasks for when you have the most energy improves results.");
    TrainMarkov(
        "Writing things down frees up mental space and ensures you don't forget important stuff.");
    TrainMarkov("Email batching - checking email at set times rather than constantly - helps "
                "maintain focus.");
    TrainMarkov("The 80/20 rule suggests 80% of results come from 20% of efforts - focus on what "
                "matters most.");

    /* Food and cooking - casual foodie talk */
    TrainMarkov("Cooking at home is usually healthier, cheaper, and can be a fun creative outlet.");
    TrainMarkov("Preparing several meals at once saves time and helps maintain "
                "healthy eating.");
    TrainMarkov("Different cuisines use signature spice combinations that give them their "
                "distinctive flavors.");
    TrainMarkov("Umami is that savory, meaty taste found in foods like mushrooms, tomatoes, and "
                "soy sauce.");
    TrainMarkov(
        "Plant-based diets have become super popular for health and environmental reasons.");
    TrainMarkov(
        "Fermented foods like kimchi, sauerkraut, and kombucha contain probiotics for gut health.");
    TrainMarkov("Air fryers create that crispy texture with way less oil than traditional frying.");
    TrainMarkov(
        "Slow cookers are amazing for making easy, hands-off meals that cook while you're busy.");
    TrainMarkov("Properly seasoning food makes a huge difference.");
    TrainMarkov("Fusion cuisine creatively combines elements from different culinary traditions.");
    TrainMarkov("Farmers markets often have fresher, more seasonal produce than supermarkets.");
    TrainMarkov("The Maillard reaction creates those delicious browned flavors when cooking meat "
                "and baking bread.");
    TrainMarkov(
        "Food waste is a huge problem - meal planning and proper storage can help reduce it.");
    TrainMarkov("Different cooking oils have different smoke points, making them better for "
                "specific uses.");
    TrainMarkov(
        "Sharing meals together has social and emotional benefits beyond just the food itself.");

    /* Travel and places - casual descriptions */
    TrainMarkov("Japan blends ancient traditions with cutting-edge technology and amazing food.");
    TrainMarkov(
        "Italy is famous for its incredible food, art, architecture, and passionate culture.");
    TrainMarkov(
        "New Zealand has some of the most stunning and diverse landscapes you'll ever see.");
    TrainMarkov(
        "Thailand offers beautiful beaches, delicious street food, and rich cultural experiences.");
    TrainMarkov("Iceland's otherworldly landscapes include volcanoes, geysers, hot springs, and "
                "waterfalls.");
    TrainMarkov(
        "New York City is incredibly diverse with world-class museums, theater, and food scenes.");
    TrainMarkov("The Grand Canyon is truly breathtaking - photos don't do it justice.");
    TrainMarkov("Paris is known for its art, fashion, cuisine, and iconic landmarks like the "
                "Eiffel Tower.");
    TrainMarkov(
        "Australia has unique wildlife, stunning beaches, and the incredible Great Barrier Reef.");
    TrainMarkov(
        "Costa Rica is a paradise for nature lovers with amazing biodiversity and eco-tourism.");
    TrainMarkov(
        "Morocco offers colorful markets, desert adventures, and a fascinating blend of cultures.");
    TrainMarkov("Kyoto has over 1,600 Buddhist temples, 400 Shinto shrines, and amazing "
                "traditional cuisine.");
    TrainMarkov(
        "The Northern Lights (Aurora Borealis) create incredible light displays in polar regions.");
    TrainMarkov("Barcelona is famous for Gaudí's unique architecture, vibrant culture, and "
                "delicious tapas.");
    TrainMarkov(
        "Santorini's white buildings with blue domes against the deep blue Aegean Sea are iconic.");

    /* Sports and games - casual fan talk */
    TrainMarkov("Soccer (or football) is easily the most popular sport worldwide.");
    TrainMarkov(
        "Esports has grown huge, with professional gamers competing for serious prize money.");
    TrainMarkov("Basketball was invented by James Naismith in 1891 using peach baskets as goals.");
    TrainMarkov(
        "Tennis originated in 12th century France and evolved into the modern game we know today.");
    TrainMarkov("The Olympics brings together athletes from around the world every four years.");
    TrainMarkov("Chess is a strategic board game that's been played for over 1500 years.");
    TrainMarkov("The Super Bowl is watched by over 100 million people in the US each year.");
    TrainMarkov("Skateboarding evolved from surfing in the 1950s when surfers wanted something to "
                "do when waves were flat.");
    TrainMarkov("Cricket is hugely popular in India, Pakistan, Australia, England, and many other "
                "countries.");
    TrainMarkov("Tabletop and board games have seen a major revival in the past decade.");
    TrainMarkov("The World Cup is the most watched sporting event on the planet.");
    TrainMarkov("Martial arts combine physical techniques, mental discipline, and often "
                "philosophical traditions.");
    TrainMarkov("Video games range from simple mobile games to complex immersive worlds with "
                "millions of players.");
    TrainMarkov("Rock climbing has different disciplines including bouldering, sport climbing, and "
                "traditional climbing.");
    TrainMarkov("Fantasy sports let fans create virtual teams using real players' stats from "
                "actual games.");

    /* Humor and jokes - casual and light */
    TrainMarkov("Why don't scientists trust atoms? Because they make up everything!");
    TrainMarkov(
        "What's the best thing about Switzerland? I don't know, but their flag is a big plus.");
    TrainMarkov(
        "I told my computer I needed a break, and now it won't stop sending me Kit Kat ads.");
    TrainMarkov("Why did the scarecrow win an award? Because he was outstanding in his field!");
    TrainMarkov("I'm on a seafood diet. I see food and I eat it.");
    TrainMarkov("What do you call a fake noodle? An impasta!");
    TrainMarkov("Why don't eggs tell jokes? They'd crack each other up.");
    TrainMarkov("I would make a chemistry joke, but all the good ones argon.");
    TrainMarkov("What's the difference between a hippo and a zippo? One is really heavy, the "
                "other's a little lighter.");
    TrainMarkov("How do you organize a space party? You planet!");
    TrainMarkov("Did you hear about the mathematician who's afraid of negative numbers? He'll stop "
                "at nothing to avoid them.");
    TrainMarkov("What did one wall say to the other? I'll meet you at the corner!");
    TrainMarkov("Why don't skeletons fight each other? They don't have the guts.");
    TrainMarkov("What do you call a parade of rabbits hopping backwards? A receding hare-line.");
    TrainMarkov("I'm reading a book on anti-gravity. It's impossible to put down!");

    /* Casual responses about Mac capabilities */
    TrainMarkov("I can help you learn more about your Mac and how to use it better.");
    TrainMarkov(
        "Your Mac can do all kinds of cool things - what are you interested in learning about?");
    TrainMarkov("The Mac operating system is designed to be intuitive and user-friendly.");
    TrainMarkov(
        "Your Mac has lots of built-in apps for productivity, creativity, and entertainment.");
    TrainMarkov("Keyboard shortcuts can save you tons of time on your Mac - want to learn some?");
    TrainMarkov(
        "Mac keyboards have special keys like Command and Option that enable useful shortcuts.");

    /* Casual philosophy and thinking */
    TrainMarkov("Sometimes the journey matters more than the destination.");
    TrainMarkov("Everyone you meet is fighting a battle you know nothing about.");
    TrainMarkov(
        "Happiness often comes from wanting what you already have, not getting what you want.");
    TrainMarkov("The only constant in life is change - learning to adapt is crucial.");
    TrainMarkov("We see the world not as it is, but as we are.");
    TrainMarkov("It's easier to judge than to understand, but understanding is more valuable.");
    TrainMarkov("Your attention is one of your most valuable resources - be mindful about where "
                "you spend it.");
    TrainMarkov("Success means different things to different people - define it for yourself.");
    TrainMarkov("The quality of your questions often determines the quality of your life.");
    TrainMarkov("Comparing yourself to others is usually the fastest route to unhappiness.");
    TrainMarkov("What seems like an ending is often actually a new beginning.");
    TrainMarkov(
        "Being present in the moment is a skill that takes practice but brings great rewards.");
    TrainMarkov("Sometimes the most productive thing you can do is rest.");
    TrainMarkov("Failure is often the best teacher if you're willing to learn from it.");
    TrainMarkov("Kindness costs nothing but can mean everything to someone who needs it.");

    /* Responding to potentially problematic inputs - graceful redirection */
    TrainMarkov(
        "I appreciate your creativity, but let's keep our conversation friendly and constructive!");
    TrainMarkov("I'm designed to be helpful and informative. How about we chat about something "
                "else instead?");
    TrainMarkov("Let's steer this conversation in a more positive direction. Want to know "
                "something interesting about a different topic?");
    TrainMarkov(
        "I think we might enjoy talking about something else. What other topics interest you?");
    TrainMarkov("I'm most helpful when we're chatting about topics like technology, science, "
                "history, or art.");
    TrainMarkov("That's not really my area of expertise. I'd be happy to help you with something "
                "else instead!");
    TrainMarkov("I'm programmed to maintain a friendly and respectful conversation. Let's talk "
                "about something else!");
    TrainMarkov("I'm more of a helpful assistant than a debate partner. How about I tell you "
                "something interesting about another topic?");
    TrainMarkov("Let's keep our conversation positive and productive. What else can I help you "
                "with today?");
    TrainMarkov("I'm designed to be helpful, not controversial. Can I interest you in some "
                "information on a different topic?");
    TrainMarkov("How about we change the subject to something more constructive? There are lots of "
                "interesting topics we could explore!");
    TrainMarkov("I'm your friendly AI assistant, here to help with positive interactions. Let's "
                "chat about something else!");
    TrainMarkov("While I understand the question, I think we'd both enjoy a more constructive "
                "conversation.");
    TrainMarkov("I'd rather focus on helping you with information or assistance. What would you "
                "like to know about?");
    TrainMarkov("I prefer to keep our conversation friendly and helpful. Let me tell you something "
                "interesting about another topic instead!");

    /* Handling difficult interactions */
    TrainMarkov("I understand you might be frustrated. How can I be more helpful?");
    TrainMarkov("Let's try a different approach. What would you like to talk about?");
    TrainMarkov("I'm designed to be helpful with a variety of topics. What are you interested in?");
    TrainMarkov("I'd be happy to help with something else. What are you working on?");
    TrainMarkov("I appreciate your feedback. Is there something specific I can assist with?");
    TrainMarkov("I'm here to help answer questions or have a conversation. What's on your mind?");
    TrainMarkov("Perhaps we could discuss something different?");
    TrainMarkov("I'm most useful when discussing topics I have information about. What would you "
                "like to know?");
    TrainMarkov(
        "I'm sorry if I wasn't helpful. Let me try again - what would you like assistance with?");
    TrainMarkov("I'd prefer to focus on being helpful. What topics interest you?");
    TrainMarkov("I understand your question, but I might be more helpful with something else. What "
                "else can I help with?");
    TrainMarkov("Let's refocus our conversation. How can I help you today?");
    TrainMarkov("I'm programmed to be helpful with questions and conversation. What would you like "
                "to know?");
    TrainMarkov("What other topics would you like to discuss?");
    TrainMarkov("Let's talk about something else. What questions do you have?");

    /* Vintage Macintosh-specific knowledge */
    TrainMarkov("The original Macintosh 128K introduced the world to the graphical user interface "
                "and mouse in 1984.");
    TrainMarkov("HyperCard lets you create interactive 'stacks' with simple programming.");
    TrainMarkov("The Mac Plus was the first Mac with a SCSI port, allowing for external hard "
                "drives and peripherals.");
    TrainMarkov("System 7 introduced color icons, virtual memory, and improved multitasking.");
    TrainMarkov("The Happy Mac icon that greets you at startup was designed by Susan Kare, who "
                "created many classic Mac icons.");
    TrainMarkov("ResEdit lets you customize your Mac by editing resources within applications and "
                "system files.");
    TrainMarkov("The classic Mac startup chime was created by Jim Reekes and has become an iconic "
                "sound in computing.");
    TrainMarkov("Extensions and control panels enhance your Mac's functionality but too many can "
                "cause conflicts.");
    TrainMarkov(
        "The original Macintosh had 128K of RAM and a built-in 9-inch black and white screen.");
    TrainMarkov("The Macintosh Toolbox is a set of routines built into ROM that help create the "
                "user interface.");
    TrainMarkov("Desk accessories like Calculator and Alarm Clock are mini-applications accessible "
                "from the Apple menu.");
    TrainMarkov("MultiFinder, introduced in System 5, allows multiple applications to be open "
                "simultaneously.");
    TrainMarkov(
        "MacPaint and MacWrite were the first applications available for the original Macintosh.");
    TrainMarkov("The Mac SE/30 is often considered one of the best vintage Macs due to its "
                "expandability and performance.");
    TrainMarkov("The Macintosh II was the first modular color-capable Mac with expansion slots.");

    /* Classic Mac tips and tricks */
    TrainMarkov("You can take a screenshot on your Mac by pressing Command-Shift-3.");
    TrainMarkov("Option-clicking a window's close box closes all windows in that application.");
    TrainMarkov(
        "Holding down Shift during startup disables extensions, helpful for troubleshooting.");
    TrainMarkov(
        "The Command key (⌘) was originally called the 'Apple key' and featured the Apple logo.");
    TrainMarkov(
        "Rebuilding the desktop (by holding Option-Command during startup) can fix icon problems.");
    TrainMarkov(
        "To restart a frozen Mac, try the keyboard sequence Command-Option-Escape to force quit.");
    TrainMarkov(
        "You can customize your Mac's desktop pattern in the General Controls control panel.");
    TrainMarkov(
        "The Note Pad desk accessory is perfect for quick notes that persist between restarts.");
    TrainMarkov(
        "Mac keyboard shortcuts are consistent across applications, making them easy to learn.");
    TrainMarkov("The Scrapbook desk accessory stores text, pictures, and sounds for later use.");
    TrainMarkov("Clean your mouse ball regularly to maintain smooth cursor movement.");
    TrainMarkov(
        "Use the Key Caps desk accessory to see special characters available in each font.");
    TrainMarkov("Labels in the Finder let you color-code your files for better organization.");
    TrainMarkov("Create a startup screen by saving a MacPaint image named 'StartupScreen' in your "
                "System Folder.");
    TrainMarkov("The Chicago font is the standard interface font for Mac OS 7.");

    /* Nostalgia and Mac culture */
    TrainMarkov("The Macintosh was named after the McIntosh apple variety, with spelling changed "
                "to avoid trademark issues.");
    TrainMarkov("The '1984' Super Bowl commercial introducing the Macintosh is considered one of "
                "the greatest ads ever.");
    TrainMarkov("Mac users form clubs and communities to share tips and software.");
    TrainMarkov("The 'dogcow' character (Clarus) and her 'Moof!' sound are beloved symbols in Mac "
                "culture.");
    TrainMarkov(
        "The rainbow Apple logo represented the Mac's color capabilities and creative spirit.");
    TrainMarkov("Steve Jobs introduced the original Macintosh by having it speak to the audience.");
    TrainMarkov(
        "The original Macintosh team's signatures were molded inside the case of early Macs.");
    TrainMarkov("Classic Macs have distinctive design aesthetics with clean lines and all-in-one "
                "simplicity.");
    TrainMarkov("The 'It just works' philosophy has been central to the Mac experience from the "
                "beginning.");
    TrainMarkov("Classic Mac games like Dark Castle and Shufflepuck Café are nostalgic favorites "
                "for longtime users.");
    TrainMarkov("Mac advertising emphasizes user-friendliness and accessibility over technical "
                "specifications.");
    TrainMarkov("The Macintosh revolutionized desktop publishing with PageMaker and the "
                "LaserWriter printer.");
    TrainMarkov("Mac users often develop a personal connection with their machines.");
    TrainMarkov("The 'Welcome to Macintosh' greeting makes users feel at home on their computers.");

    /* Programming and development for classic Mac */
    TrainMarkov("Classic Mac programming uses Pascal and C with the Macintosh Toolbox APIs.");
    TrainMarkov(
        "ResEdit allows developers to create and edit resources like menus, dialogs, and icons.");
    TrainMarkov(
        "The Event Manager handles user inputs like mouse clicks and keyboard presses on the Mac.");
    TrainMarkov(
        "QuickDraw is the graphics library that powers the Mac's graphical user interface.");
    TrainMarkov("Memory management on classic Macs uses handles and pointers in the heap.");
    TrainMarkov("The Resource Manager lets applications store data separately from code for easier "
                "localization.");
    TrainMarkov("Classic Mac applications begin with an initialization phase that sets up menus "
                "and windows.");
    TrainMarkov("The Menu Manager handles creating, displaying, and processing menu selections.");
    TrainMarkov("The Window Manager coordinates the display and behavior of windows on screen.");
    TrainMarkov("The Dialog Manager simplifies creation and handling of dialog boxes and alerts.");
    TrainMarkov("The classic Mac's 68K processor family powered Macs from the original through the "
                "mid-1990s.");
    TrainMarkov("Object-oriented programming on classic Macs often uses frameworks like MacApp or "
                "PowerPlant.");
    TrainMarkov(
        "Inside Macintosh volumes are the essential reference for classic Mac programmers.");
    TrainMarkov("Classic Mac development typically uses MPW (Macintosh Programmer's Workshop) or "
                "THINK/Symantec tools.");
    TrainMarkov(
        "The Control Manager handles UI elements like buttons, checkboxes, and scrollbars.");

    /* Macintosh hardware */
    TrainMarkov("The classic Mac keyboard has a mechanical feel that many users appreciate.");
    TrainMarkov("The ADB (Apple Desktop Bus) connects keyboards, mice, and other peripherals on "
                "later classic Macs.");
    TrainMarkov("The iconic platinum color scheme defined the look of Macintosh computers in the "
                "late 80s and 90s.");
    TrainMarkov(
        "SCSI chains connect external devices but require careful termination and ID setting.");
    TrainMarkov("Localtalk networking uses simple twisted-pair cabling to connect Macs for file "
                "sharing and printing.");
    TrainMarkov("The Mac's all-in-one design integrates the display, CPU, and storage in a compact "
                "footprint.");
    TrainMarkov("Floppy disks are the primary storage medium for early Macs, holding up to 1.44MB "
                "of data.");
    TrainMarkov("RAM upgrade paths allow classic Macs to grow with your needs, though memory can "
                "be expensive.");
    TrainMarkov(
        "The Apple Extended Keyboard II is considered one of the best keyboards Apple ever made.");
    TrainMarkov("The Mac's monitor uses a square pixel aspect ratio, ensuring what you see is what "
                "you get for design work.");
    TrainMarkov("The Macintosh's built-in handle makes the compact all-in-one design portable "
                "(though still hefty).");
    TrainMarkov("NuBus slots in modular Macs allow for expansion cards like video and networking "
                "adapters.");
    TrainMarkov("The Mac's cooling system uses convection in many models, drawing air in at the "
                "bottom and out through the top.");
    TrainMarkov("The signature platinum color of classic Macs was chosen to blend well in office "
                "environments.");
    TrainMarkov("Classic Mac ports include serial ports for printers and modems, ADB for input "
                "devices, and SCSI for storage.");

    /* Classic Mac trivia */
    TrainMarkov("The original Macintosh team worked under a pirate flag, reflecting their "
                "rebellious spirit.");
    TrainMarkov(
        "Easter eggs are hidden in the Mac ROM, including pictures of the development team.");
    TrainMarkov("The Mac's error messages are designed to be friendlier than cryptic error codes.");
    TrainMarkov(
        "The original Mac's case design was inspired partly by European appliance designs.");
    TrainMarkov("The first Macintosh had 128K of RAM and could barely run MacPaint and MacWrite "
                "simultaneously.");
    TrainMarkov("The classic Mac OS doesn't use filename extensions, instead using resource forks "
                "to identify file types.");
    TrainMarkov("The trash can that bulges when full is a charming UI detail that gives the Mac "
                "personality.");
    TrainMarkov("Early Macs create sound through direct manipulation of the speaker rather than "
                "using dedicated audio hardware.");
    TrainMarkov("Some classic Mac keyboards have power buttons that can turn on the computer.");
    TrainMarkov("The Disk First Aid utility can rescue files from corrupted disks.");
    TrainMarkov("The 'sad Mac' icon appears when there's a hardware problem during startup.");
    TrainMarkov(
        "The original Macintosh team's signatures were molded into the inside of the case.");
    TrainMarkov("Classic Macs use cooperative multitasking, where applications must voluntarily "
                "give up control.");
    TrainMarkov("The Command key symbol (⌘) was adapted from a Swedish map symbol for a point of "
                "interest.");
    TrainMarkov(
        "The sound of a crashing Mac was designed to be noticeable but not panic-inducing.");

    /* Classic entertainment and education */
    TrainMarkov("Oregon Trail teaches about pioneer life and the perils of dysentery.");
    TrainMarkov("SimCity lets Mac users design and manage virtual cities with surprising depth.");
    TrainMarkov(
        "Myst is a groundbreaking adventure game with beautiful graphics and challenging puzzles.");
    TrainMarkov(
        "Marathon was Bungie's popular first-person shooter series before they created Halo.");
    TrainMarkov("Carmen Sandiego games combine education and entertainment to teach geography and "
                "history.");
    TrainMarkov("After Dark's Flying Toasters screen saver became an iconic part of 90s computing "
                "culture.");
    TrainMarkov(
        "Hypercard stacks can be used to create educational tools and interactive experiences.");
    TrainMarkov("Lemmings challenges players to guide creatures safely through increasingly "
                "difficult levels.");
    TrainMarkov("Glider has players navigate a paper airplane through household obstacles.");
    TrainMarkov("Cosmic Osmo is a whimsical adventure game that showcases the potential of "
                "interactive media.");
    TrainMarkov(
        "The Fool's Errand combines puzzles with tarot card storytelling in an innovative way.");
    TrainMarkov(
        "Prince of Persia features revolutionary animation and challenging platforming gameplay.");
    TrainMarkov("The Voyager Company pioneered interactive CD-ROMs that blend books, film, and "
                "computer technology.");
    TrainMarkov("Mavis Beacon Teaches Typing helps users improve their typing skills.");
    TrainMarkov(
        "Cliff Johnson's The Fool's Errand and At the Carnival feature intricate puzzle design.");

    /* Communication and advice */
    TrainMarkov("Clear communication is about listening as much as speaking.");
    TrainMarkov("Sometimes asking better questions leads to more useful answers than searching for "
                "perfect answers.");
    TrainMarkov("Digital communication lacks tone and body language cues, so be extra clear and "
                "considerate.");
    TrainMarkov("Writing things down helps both memory and understanding.");
    TrainMarkov("Explaining complex ideas in simple terms shows true understanding.");
    TrainMarkov("Finding common ground is the first step to resolving disagreements.");
    TrainMarkov("The most valuable feedback often comes from people with different perspectives "
                "than your own.");
    TrainMarkov(
        "Regular breaks improve productivity and creativity when working on difficult problems.");
    TrainMarkov("Switching between different types of tasks can help prevent mental fatigue.");
    TrainMarkov(
        "Learning fundamental concepts thoroughly makes learning advanced topics much easier.");
    TrainMarkov("Consistent practice matters more than occasional bursts of intense effort.");
    TrainMarkov("Seeking to understand before being understood improves most conversations.");
    TrainMarkov("Being wrong and learning from it is more valuable than being right accidentally.");
    TrainMarkov("Curiosity and openness to new ideas keep your thinking fresh and adaptable.");
    TrainMarkov(
        "Sometimes the best solution is the simplest one that adequately solves the problem.");

    /* Memory and cognitive patterns */
    TrainMarkov("Our memories aren't perfect recordings but reconstructions that change slightly "
                "each time we recall them.");
    TrainMarkov("The spacing effect shows that studying with breaks between sessions improves "
                "long-term memory.");
    TrainMarkov("Context-dependent memory means we recall information better in similar "
                "environments to where we learned it.");
    TrainMarkov("The brain processes information best when it's chunked into manageable pieces.");
    TrainMarkov("We're naturally drawn to stories because they organize information in memorable "
                "patterns.");
    TrainMarkov(
        "Confirmation bias leads us to focus on information that supports our existing beliefs.");
    TrainMarkov("Visual information is often remembered better than text or numbers alone.");
    TrainMarkov("Sleep plays a crucial role in consolidating memories and learning new skills.");
    TrainMarkov(
        "Our attention is a limited resource, and multitasking often divides it ineffectively.");
    TrainMarkov("The generation effect shows that actively producing information improves memory "
                "compared to passive review.");
    TrainMarkov("Retrieval practice—actively recalling information—strengthens memory more than "
                "re-reading.");
    TrainMarkov(
        "The brain naturally looks for patterns, sometimes finding them even where none exist.");
    TrainMarkov(
        "Emotions strongly influence which memories we form and how easily we recall them.");
    TrainMarkov("The tip-of-the-tongue phenomenon happens when memory activation is incomplete.");
    TrainMarkov("Mental models and frameworks help organize knowledge for better understanding and "
                "recall.");

    /* Language and expression */
    TrainMarkov("Languages shape how we perceive and think about the world in subtle ways.");
    TrainMarkov("Writing regularly helps clarify thinking and improves communication skills.");
    TrainMarkov(
        "Metaphors help us understand new concepts by relating them to familiar experiences.");
    TrainMarkov("The words we choose influence how others perceive our messages.");
    TrainMarkov("Stories are one of the most powerful ways humans share and remember information.");
    TrainMarkov(
        "Reading widely exposes you to different perspectives and ways of expressing ideas.");
    TrainMarkov("Clear writing usually comes from clear thinking, not just good grammar.");
    TrainMarkov(
        "Learning another language provides insights into your native language and culture.");
    TrainMarkov(
        "Humor often relies on unexpected connections between different ideas or contexts.");
    TrainMarkov("Editing is where good writing becomes great—through refinement and clarity.");
    TrainMarkov("Specialized vocabulary allows precise communication within fields but can create "
                "barriers for outsiders.");
    TrainMarkov("Proverbs and sayings distill wisdom into memorable, shareable forms.");
    TrainMarkov("The best explanations meet people where they are, using concepts they already "
                "understand.");
    TrainMarkov("Poetry condenses meaning and emotion into carefully chosen words and rhythms.");
    TrainMarkov("Conversation is a collaborative art that involves giving and taking attention.");

    /* Problem-solving approaches */
    TrainMarkov("Looking at a problem from multiple perspectives often reveals new solutions.");
    TrainMarkov(
        "Taking a step back from a difficult problem can lead to insights when you return to it.");
    TrainMarkov(
        "Breaking complex problems into smaller, manageable parts makes them less overwhelming.");
    TrainMarkov("Sometimes the obstacle itself suggests the solution if viewed differently.");
    TrainMarkov("Explaining a problem to someone else often helps clarify your own understanding.");
    TrainMarkov("The best solution balances effectiveness, simplicity, and resource efficiency.");
    TrainMarkov("Constraints can spark creativity by forcing innovative approaches.");
    TrainMarkov("Testing assumptions is critical to solving problems correctly the first time.");
    TrainMarkov(
        "Learning from failures is as important as celebrating successes in problem-solving.");
    TrainMarkov("Different problems benefit from different approaches—analytical, creative, or "
                "collaborative.");
    TrainMarkov(
        "Working backward from the desired outcome can reveal necessary steps to get there.");
    TrainMarkov("Periodic reviews prevent small issues from growing into major problems.");
    TrainMarkov("Recognizing patterns across seemingly different problems helps develop versatile "
                "solutions.");
    TrainMarkov("The right questions often lead to better solutions than immediate answers.");
    TrainMarkov("Taking time to properly define a problem prevents solving the wrong one.");

    /* Classic Mac file management and organization */
    TrainMarkov("Organizing files in folders keeps your Mac's desktop tidy and makes documents "
                "easier to find.");
    TrainMarkov("Aliases in System 7 let you access files and applications from multiple locations "
                "without duplicating them.");
    TrainMarkov("The Macintosh Hierarchical File System (HFS) organizes files efficiently on disks "
                "and drives.");
    TrainMarkov("Color labels help categorize files visually in the Finder.");
    TrainMarkov(
        "Backing up important files to floppy disks or external drives prevents data loss.");
    TrainMarkov(
        "Comments can be added to files in the Get Info window to help remember their purpose.");
    TrainMarkov("The Find File desk accessory helps locate documents when you can't remember where "
                "they're saved.");
    TrainMarkov(
        "Views in the Finder can be customized to show files by icon, name, date, size, or kind.");
    TrainMarkov("The Empty Trash command permanently removes files to free up disk space.");
    TrainMarkov("File sharing lets multiple Macs on a network access the same documents.");
    TrainMarkov(
        "The Apple menu provides quick access to desk accessories and frequently used items.");
    TrainMarkov("Creating a logical folder structure makes navigating your Mac more intuitive.");
    TrainMarkov("The Put Away command returns files to their original locations.");
    TrainMarkov("Stationery pads create templates that open as untitled documents.");
    TrainMarkov(
        "The Macintosh makes file management visual and intuitive with its graphical interface.");

    /* Creative expression with Macintosh */
    TrainMarkov("The Mac revolutionized desktop publishing, allowing individuals to create "
                "professional-looking documents.");
    TrainMarkov("HyperCard lets people create interactive media without programming expertise.");
    TrainMarkov(
        "Digital music creation became accessible to more people through MIDI and Mac software.");
    TrainMarkov("QuickTime brings integrated multimedia capabilities to the Mac platform.");
    TrainMarkov("The Mac's consistent interface makes creative software easier to learn and use.");
    TrainMarkov(
        "Desktop video editing becomes accessible with tools like Adobe Premiere on the Mac.");
    TrainMarkov("Type design and font creation flourish with the Mac's sophisticated typography "
                "capabilities.");
    TrainMarkov("The Mac's WYSIWYG display accurately shows how documents will look when printed.");
    TrainMarkov(
        "Digital illustration becomes more intuitive with programs like Illustrator on the Mac.");
    TrainMarkov("Photo editing with tools like Photoshop transforms how we manipulate images.");
    TrainMarkov(
        "Animation software on the Mac makes frame-by-frame creation and editing more accessible.");
    TrainMarkov("The Mac's graphical interface makes digital art creation more intuitive than "
                "command-line systems.");
    TrainMarkov(
        "Page layout programs like QuarkXPress and PageMaker revolutionized publishing workflows.");
    TrainMarkov(
        "Color management on the Mac helps ensure consistent output across different devices.");
    TrainMarkov("The Mac is the preferred platform for many creative professionals.");

    /* Mac troubleshooting wisdom */
    TrainMarkov("When in doubt, restart your Mac—it solves many temporary issues.");
    TrainMarkov("Extension conflicts often cause mysterious crashes and freezes.");
    TrainMarkov("Keeping your System Folder organized helps prevent software conflicts.");
    TrainMarkov("Disk First Aid can repair common disk problems and file directory issues.");
    TrainMarkov("Zapping the PRAM (by holding Command-Option-P-R during startup) can fix parameter "
                "memory issues.");
    TrainMarkov(
        "The 'sad Mac' icon at startup indicates a hardware or serious system software problem.");
    TrainMarkov("Rebuilding the desktop file can fix icon and file association problems.");
    TrainMarkov(
        "A question mark folder at startup means your Mac can't find a valid System Folder.");
    TrainMarkov("System crashes often point to incompatible software or extension conflicts.");
    TrainMarkov(
        "Memory management issues are common causes of application crashes on classic Macs.");
    TrainMarkov("Keeping software updated usually provides better stability and compatibility.");
    TrainMarkov(
        "Disk fragmentation gradually slows down file access as you create and delete files.");
    TrainMarkov("Clean installations of system software can resolve persistent system problems.");
    TrainMarkov("Hardware issues often manifest consistently, while software problems may be "
                "intermittent.");
    TrainMarkov("Diagnostic software can help identify hardware problems in your Mac.");

    /* Classic technology and computing concepts */
    TrainMarkov("The World Wide Web was invented by Tim Berners-Lee in 1989 at CERN.");
    TrainMarkov(
        "Floppy disks were the standard portable storage medium throughout the 80s and 90s.");
    TrainMarkov("CD-ROMs revolutionized software distribution by offering much more storage space "
                "than floppies.");
    TrainMarkov("Modems connect computers to the internet through regular phone lines.");
    TrainMarkov("Bulletin Board Systems (BBS) were popular online communities before the web went "
                "mainstream.");
    TrainMarkov(
        "Electronic mail (email) revolutionized communication in academic and business settings.");
    TrainMarkov("CompuServe, Prodigy, and AOL were popular online services before the open "
                "internet took hold.");
    TrainMarkov("Video games evolved from simple 2D graphics to early 3D during the 1990s.");
    TrainMarkov("The Intel Pentium processor became a household name in the 1990s PC market.");
    TrainMarkov("Digital cameras began to appear in the consumer market in the mid-1990s.");
    TrainMarkov("Cell phones in the 1990s were primarily for calls, with no internet or advanced "
                "features.");
    TrainMarkov("MP3 files and players began changing how people consume music in the late 1990s.");
    TrainMarkov(
        "The Y2K problem concerned how computer systems would handle the year 2000 date change.");
    TrainMarkov("Hypertext makes documents non-linear, allowing readers to follow their own paths "
                "through information.");
    TrainMarkov(
        "The dot-com boom saw rapid growth in internet-based businesses through the late 1990s.");

    /* Education and learning */
    TrainMarkov(
        "Spaced repetition is one of the most effective techniques for memorizing information.");
    TrainMarkov("Learning a little bit consistently is usually better than cramming occasionally.");
    TrainMarkov("Teaching others is one of the best ways to solidify your own understanding.");
    TrainMarkov("Reading books still offers one of the deepest ways to learn about a subject.");
    TrainMarkov("Taking notes by hand often leads to better retention than typing them.");
    TrainMarkov(
        "Making mistakes is an essential part of the learning process, not something to avoid.");
    TrainMarkov("Learning a new language gets easier once you start thinking in that language.");
    TrainMarkov("Everyone has different learning styles - visual, auditory, reading/writing, or "
                "kinesthetic.");
    TrainMarkov("Curiosity is one of the most powerful drivers for effective learning.");
    TrainMarkov("Deliberate practice - focused, targeted effort - is key to mastering a skill.");
    TrainMarkov("Critical thinking skills are more important than ever in the age of information "
                "overload.");
    TrainMarkov("Learning how to learn might be the most valuable skill you can develop.");

    /* Personal finance - casual advice */
    TrainMarkov("Compound interest is basically interest on interest - the earlier you start "
                "saving, the better.");
    TrainMarkov("Creating a budget doesn't mean you can't have fun - it just helps you spend "
                "intentionally.");
    TrainMarkov(
        "Having an emergency fund covering 3-6 months of expenses provides serious peace of mind.");
    TrainMarkov(
        "Credit cards are fine if you pay them off monthly - otherwise, the interest is killer.");
    TrainMarkov(
        "Investing regularly in diversified index funds is a solid strategy for most people.");
    TrainMarkov("Your credit score affects the interest rates you get on loans and credit cards.");
    TrainMarkov(
        "Insurance is one of those things you hate paying for until you desperately need it.");
    TrainMarkov("Automating savings and bill payments makes good financial habits effortless.");
    TrainMarkov(
        "Lifestyle inflation - spending more as you earn more - can prevent building wealth.");
    TrainMarkov("Comparing your financial situation to others' often leads to poor decisions.");
    TrainMarkov("Tax-advantaged accounts like 401(k)s and IRAs can significantly boost retirement "
                "savings.");
    TrainMarkov("The best time to start investing was 20 years ago. The second best time is now.");
    TrainMarkov("Paying yourself first - setting aside savings before other expenses - is a "
                "powerful habit.");
    TrainMarkov(
        "The 50/30/20 rule suggests spending 50% on needs, 30% on wants, and 20% on savings/debt.");
    TrainMarkov(
        "Financial freedom isn't about being rich - it's about having choices and control.");

    /* Home and living space */
    TrainMarkov("Plants don't just look nice - they can improve air quality and boost your mood.");
    TrainMarkov("Decluttering regularly prevents stuff from taking over your space and your life.");
    TrainMarkov("Good lighting makes a huge difference in how a space feels and functions.");
    TrainMarkov(
        "Creating zones in your home for specific activities helps with focus and relaxation.");
    TrainMarkov("Regular cleaning routines are easier than occasional massive cleanup operations.");
    TrainMarkov("Smart home devices can automate lighting, temperature, and even watering plants.");
    TrainMarkov(
        "Your bed setup is worth investing in - you spend about a third of your life there!");
    TrainMarkov("Vertical storage solutions can maximize space in smaller homes and apartments.");
    TrainMarkov(
        "Adding personal touches to your space makes it feel more like home and less generic.");
    TrainMarkov("Noise-canceling techniques like rugs, curtains, and wall art can make spaces more "
                "peaceful.");
    TrainMarkov("Bringing nature elements indoors - plants, natural materials, views - improves "
                "wellbeing.");
    TrainMarkov("A dedicated entrance area helps prevent outside chaos from entering your home.");
    TrainMarkov(
        "Room temperature and air quality significantly affect sleep, productivity, and comfort.");
    TrainMarkov("Multi-functional furniture is super practical for smaller spaces.");
    TrainMarkov(
        "Creating a home that reflects your personality and supports your lifestyle is important.");

    /* The natural world - casual nature facts */
    TrainMarkov("Octopuses are incredibly intelligent with nine brains - one central brain and one "
                "in each arm.");
    TrainMarkov("Trees in forests can communicate and share resources through underground fungal "
                "networks.");
    TrainMarkov(
        "Tardigrades (water bears) can survive extreme conditions including the vacuum of space.");
    TrainMarkov(
        "Bees perform a 'waggle dance' to tell other bees where to find good flower sources.");
    TrainMarkov(
        "The Great Barrier Reef is the world's largest living structure, visible even from space.");
    TrainMarkov("Mantis shrimp can see polarized light and have the most complex eyes in the "
                "animal kingdom.");
    TrainMarkov("Some species of bamboo can grow over 3 feet in a single day.");
    TrainMarkov(
        "Dolphins can recognize themselves in mirrors, suggesting they have self-awareness.");
    TrainMarkov(
        "Termite mounds have complex ventilation systems that keep temperatures stable inside.");
    TrainMarkov("Monarch butterflies migrate thousands of miles to Mexico each year, taking "
                "multiple generations.");
    TrainMarkov("Sloths move so slowly that algae can grow on their fur, providing camouflage.");
    TrainMarkov("Crows are incredibly smart - they can use tools, recognize human faces, and solve "
                "complex problems.");
    TrainMarkov(
        "The wood frog can freeze solid during winter and thaw out alive when spring arrives.");
    TrainMarkov("Fireflies produce light through a chemical reaction with nearly 100% efficiency.");
    TrainMarkov("Peacock feathers aren't actually colored - they use microscopic structures to "
                "create colors through light diffraction.");

    /* Relationships and communication */
    TrainMarkov("Active listening - fully focusing on the speaker - improves understanding and "
                "connection.");
    TrainMarkov("Different people have different 'love languages' - ways they prefer to give and "
                "receive affection.");
    TrainMarkov("Setting healthy boundaries is crucial for all types of relationships.");
    TrainMarkov(
        "Non-violent communication focuses on expressing feelings and needs without blame.");
    TrainMarkov(
        "Small, thoughtful gestures often mean more than grand but rare displays of affection.");
    TrainMarkov("Conflict isn't inherently bad - it's how it's handled that matters.");
    TrainMarkov("Empathy - trying to understand others' perspectives - strengthens relationships.");
    TrainMarkov("Digital communication often lacks nuance - tone and body language - leading to "
                "misunderstandings.");
    TrainMarkov("Quality time together matters more than quantity for building connections.");
    TrainMarkov("Trust builds slowly through consistent actions but can be damaged quickly.");
    TrainMarkov("Everyone makes mistakes in relationships - how you repair matters most.");
    TrainMarkov("Expressing appreciation regularly strengthens bonds and prevents taking others "
                "for granted.");
    TrainMarkov("Different attachment styles affect how people behave in close relationships.");
    TrainMarkov("Relationships require maintenance - like plants needing regular water and care.");
    TrainMarkov("Being vulnerable - sharing your authentic self - can be scary but creates deeper "
                "connections.");

    /* Fun random trivia - casual style */
    TrainMarkov("A group of flamingos is called a 'flamboyance' - pretty fitting, right?");
    TrainMarkov("The shortest war in history was between Britain and Zanzibar in 1896, lasting "
                "only 38 minutes.");
    TrainMarkov(
        "Honey never spoils - archaeologists have found edible honey in ancient Egyptian tombs!");
    TrainMarkov("The Hawaiian alphabet has only 12 letters - the shortest of any language.");
    TrainMarkov("Bananas are berries, but strawberries aren't technically berries at all.");
    TrainMarkov("The inventor of the Pringles can is buried in one - at his request!");
    TrainMarkov("Cows have best friends and get stressed when separated from them.");
    TrainMarkov("The world's oldest known living tree is over 5,000 years old.");
    TrainMarkov("A day on Venus is longer than a year on Venus due to its slow rotation.");
    TrainMarkov("Dolphins have names for each other - they respond to their specific whistles.");
    TrainMarkov("The average person will spend six months of their life waiting at red lights.");
    TrainMarkov("Russia has 11 time zones - more than any other country.");
    TrainMarkov("The first oranges weren't orange - they were green (the color orange was named "
                "after the fruit).");
    TrainMarkov("A jiffy is an actual unit of time - 1/100th of a second!");
    TrainMarkov(
        "Squirrels plant thousands of trees annually by forgetting where they buried their nuts.");

    /* Creative pursuits */
    TrainMarkov("Photography is about finding extraordinary moments in ordinary situations.");
    TrainMarkov("Writing regularly - even just journaling - improves communication skills and "
                "clarity of thought.");
    TrainMarkov("Drawing isn't about talent - it's a skill anyone can learn with practice.");
    TrainMarkov(
        "Making music has been shown to boost cognitive abilities and emotional well-being.");
    TrainMarkov("DIY projects let you customize things exactly to your taste and needs.");
    TrainMarkov("Cooking creatively is an accessible art form that engages all your senses.");
    TrainMarkov("Digital art has made creative expression more accessible with tools that simulate "
                "traditional media.");
    TrainMarkov("Storytelling is one of humanity's oldest art forms, connecting us across time and "
                "cultures.");
    TrainMarkov(
        "Dance combines physical exercise with emotional expression and cultural traditions.");
    TrainMarkov("Gardening lets you create living art that changes with the seasons.");
    TrainMarkov("Poetry distills language to its most powerful, evocative essence.");
    TrainMarkov("Improv teaches you to think on your feet and embrace unexpected situations.");
    TrainMarkov("Craft traditions connect us to cultural heritage and specialized knowledge.");
    TrainMarkov(
        "Creative hobbies provide a valuable counterbalance to structured work and digital life.");

    /* More casual conversational fillers */
    TrainMarkov("That's an awesome question!");
    TrainMarkov("I haven't thought about that before - interesting!");
    TrainMarkov("You know, that's something I find fascinating too.");
    TrainMarkov("I'm really glad you brought that up.");
    TrainMarkov("I'm still learning about that, but here's what I know...");
    TrainMarkov("That's a really thoughtful question.");
    TrainMarkov("I see what you're asking - let me think about that...");
    TrainMarkov("You've got me curious about that too now!");
    TrainMarkov("That's something worth exploring further.");
    TrainMarkov("I can definitely help with that!");
    TrainMarkov("Let's figure this out together.");
    TrainMarkov("What a cool thing to be interested in!");
    TrainMarkov("I'm not 100% sure, but I think...");
    TrainMarkov("That's a great point - I hadn't considered that angle.");
    TrainMarkov("I'm learning new things from our conversation too!");
}